name: 레이블 이름 검증

run-name: "레이블 '${{ github.event.label.name }}' 이름 검증"

on: 
  label:
    types:
      - created

jobs:
  validate-label:
    runs-on: ubuntu-latest
    steps: 
      - name: Check label name
        run: |
          echo "Checking label: ${{ github.event.label.name }}"
          if [[ ! "${{ github.event.label.name }}" =~ ^[a-z\ ]+$ ]]; then
            echo "❌ 레이블 이름은 소문자 및 띄어쓰기만 허용됩니다."
            exit 1
          fi
