name: PR CI

on:
  pull_request:
    branches: [dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  run-tests:
    uses: ./.github/workflows/build-and-test.yml
    with:
      api-level: 33
